apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappdemo
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: hailt88/rabbitmq:a2c1fb4
        ports:
        - containerPort: 8080
